# 1. Database Connection (Replaces setDevProperties)
spring.datasource.url=jdbc:postgresql://localhost:5432/streaming_system
spring.datasource.username=postgres
spring.datasource.password=postgres

# 2. Hibernate Settings (Replaces setBaseProperties)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# 3. Server Settings (Replaces AppConfig startServer)
server.port=8081
server.servlet.context-path=/api

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG